version: '3.3'

services:

 frontend:
  build: jstoneqa/sfia-2-jenkins_frontend
  expose:
   - 5000
  depends_on:
   - backend

 backend:
  build: jstoneqa/sfia-2-jenkins_backend
  expose:
   - 5001 
  depends_on:
   - database
  environment:
   - DATABASE_URI=${DATABASE_URI}
   - SECRET_KEY=${SECRET_KEY}
   - TEST_DATABASE_URI=${TEST_DATABASE_URI}

 database:
  build: jstoneqa/sfia-2-jenkins_database
  environment:
   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  expose:
   - 3306
  volumes:
   - type: volume
     source: jenkins
     target: /var/jenkins_home

 nginx:
  image: nginx
  ports:
   - "80:80"
  volumes:
   - type: bind
     source: ./nginx/nginx.conf
     target: /etc/nginx/nginx.conf  
  depends_on:
   - frontend

volumes:
 jenkins:

