version: '3.3'

services:

 frontend:
  build: ./frontend
  expose:
   - 5000
  depends_on:
   - backend

 backend:
  build: ./backend
  expose:
   - 5001 
  depends_on:
   - database
  environment:
   - DATABASE_URL=${DATABASE_URL}
   - SECRET_KEY=${SECRET_KEY}

 database:
  build: ./database
  environment:
   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  expose:
   - 3306
  volumes:
   - type: volume
  source: jenkins
  target: /var/jenkins_home

 nginx:
  build: ./nginx
  ports:
   - "80:80"
  volumes:
   - type: bind
     source: ./nginx/nginx.conf
     target: /etc/nginx/nginx.conf  

volumes:
 jenkins:

