version: '3.3'

services:

 frontend:
  build: ./frontend
  ports:
   - "5001:80"
  depends_on:
   - backend
#   - database
  networks:
   - front-end-net
   - back-end-net

 backend:
  build: ./backend
  ports:
   - "5000:80"
#  depends_on:
#   - database
  networks:
   - front-end-net
   - back-end-net

# database: 
#  build: ./database
#  networks:
#   - back-end-net
#  ports:
#   - "3306:3306"

 nginx:
  build: ./nginx
  networks:
   - front-end-net
  ports:
   - "80:80"
  volumes:
   - type: bind
     source: ./nginx/nginx.conf
     target: /etc/nginx/nginx.conf  

networks:
 front-end-net:
 back-end-net: 
