apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports: 
  - protocol: TCP
    port: 5001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels: 
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jstoneqa/sfia-2-jenkins_backend
        ports:
          - containerPort: 5001
        env:
          - name: TEST_DATABASE_URI
            value: $TEST_DATABASE_URI
          - name: DATABASE_URI
            value: $DATABASE_URI
          - name: SECRET_KEY
            value: $SECRET_KEY
